services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  roadrunner:
    entrypoint: ["rr", "serve", "-d", "-c", "/app/.rr.dev.yaml"]
    depends_on:
      - postgres

volumes:
  pgdata: